# Inspired from https://medium.com/@sunnykay/docker-development-workflow-node-express-mongo-4bb3b1f7eb1e
version: "2"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=chris.uehlinger@gmail.com
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db